[project]
name = "second-brain-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Mohammad Rezazade", email = "mrprocs@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "celery[redis]>=5.6.3",
    "ddgs>=9.16.0",
    "httpx>=0.28.1",
    "ollama>=0.6.2",
    "pydantic-settings>=2.15.0",
    "python-telegram-bot>=22.8",
]

[project.scripts]
second-brain-bot = "second_brain_bot.main:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pyright>=1.1.414",
    "pytest>=9.1.1",
    "ruff>=0.16.7",
]
